version: '3.6'

services:
  library:
    build:
      context: .
      dockerfile: library/src/main/resources/library.dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - network1
networks:
  network1:
    driver: bridge